# fly.toml app configuration file generated for liz-wa-webhook on 2026-01-12T11:54:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liz-wa-webhook'
primary_region = 'gru'

[build]

[processes]
  api = "node dist/index.js"
  worker = "node dist/worker.js"

[http_service]
  internal_port = 8080
  processes = ["api"]
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
